language: node_js

node_js:
- "11"

before_script:
- npm run build

script:
- npm test
- npm run coveralls

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- npx version-from-git --travis

deploy:
- provider: npm
  api_key:
    secure: "L7CWVEOs6/oVmGjURos8e+rT9OBdKZ26qCdlYdqSy1ER5clbukpHsK/loidFkhjTpgje6E0UYpNaChhcmSZauqY4PeYef4p327q7e52gbR9wHaXzuEPYc/+QQGhUY86BAtjaKGILUKNmjSk94/VV6UGIkHXzecVE/watmVs45rlezf/j5RJn6nfvV4x2mVacYmZaJ/d4+EsRJWyR/MeVOajQjH1KUF3CIRkOICm2fi3kPsbSGj2r3bp+iWz/C7/9BRw93kQKiDK9xz1qJ0EXsPq5+tLEFXbR93XgfG+XRO0OKT+e6aqT8oZ6YKF+UGlT00bkBLnzYLqq8QlvmjOxz0p0n5wAiv9VBG57tZqhgsXCeuhBsMLeDi9ACSdw8j7KPiYuAEyBgzaXCgQ/L3vLZ6ZHWrnStdl1+/8JcL82AdcIRoNqo0BZYDLcI5PA8vUYh2deC/ccE0PWJ5stIyPCXNzkk4IYi9hDt2STi/xcCKHsI8+QLZdF2nojYtqN3nh/cXWBJEfnLs3bEj74ulGj9tNAz9I6nz80COvCJUY1kulgyG6FcDM5WpEXABEDW+O63rIKowc7sGZgCc2fnkU91n651r70ym0/k72rwefFsFf3OPeusFxWhuC04O/CE9A4JVE9BnzvFdgcGF53YiiSTI7a+vyYB53USDeYEhpVkn8="
  email: "compulim@hotmail.com"
  on:
    branch: master
  skip_cleanup: true
  tag: master

- provider: npm
  api_key:
    secure: "L7CWVEOs6/oVmGjURos8e+rT9OBdKZ26qCdlYdqSy1ER5clbukpHsK/loidFkhjTpgje6E0UYpNaChhcmSZauqY4PeYef4p327q7e52gbR9wHaXzuEPYc/+QQGhUY86BAtjaKGILUKNmjSk94/VV6UGIkHXzecVE/watmVs45rlezf/j5RJn6nfvV4x2mVacYmZaJ/d4+EsRJWyR/MeVOajQjH1KUF3CIRkOICm2fi3kPsbSGj2r3bp+iWz/C7/9BRw93kQKiDK9xz1qJ0EXsPq5+tLEFXbR93XgfG+XRO0OKT+e6aqT8oZ6YKF+UGlT00bkBLnzYLqq8QlvmjOxz0p0n5wAiv9VBG57tZqhgsXCeuhBsMLeDi9ACSdw8j7KPiYuAEyBgzaXCgQ/L3vLZ6ZHWrnStdl1+/8JcL82AdcIRoNqo0BZYDLcI5PA8vUYh2deC/ccE0PWJ5stIyPCXNzkk4IYi9hDt2STi/xcCKHsI8+QLZdF2nojYtqN3nh/cXWBJEfnLs3bEj74ulGj9tNAz9I6nz80COvCJUY1kulgyG6FcDM5WpEXABEDW+O63rIKowc7sGZgCc2fnkU91n651r70ym0/k72rwefFsFf3OPeusFxWhuC04O/CE9A4JVE9BnzvFdgcGF53YiiSTI7a+vyYB53USDeYEhpVkn8="
  email: "compulim@hotmail.com"
  on:
    tags: true
  skip_cleanup: true

- provider: releases
  api_key:
    secure: "kbqAf2m2QvG6yAQWvBZAXKhW3MQ6zXEL0OxPQ2IEUFEODjXLwW0WLfiXzXdPHDf2hAUSVrtPE0fR89ya4Fr3BPn1S7pCE9WHKLt+AviLY+Mml99b1l1icpApYK++rNr+mqWoM86LSWh59FaFVlG4hcPglQSoeAZRbACRyUhzItcHs/pOYxRNRuRM83VPhbi3xd36amu/KmEsYAlhK1OF5fQNMiFrJZ8V3otAU2vfcOSYrvlGV09Qt4ayedibAvM+zdkQj15caliGw1xsanMufTe5pXHnGZORRWOfMbd3RXKIazdJYQCIpRGDhjOjzSDogLBcaThsft2m8Ur86tF94k7kl4DVH6HSJ3MEertLqmmCOWjpSJ9KsALYy+J6RLSXdR43p7aZQOUD+wLMTg1B3aZ4TND3g0BsIysstbp+SFCVsRJwCleJ4GyTOVg+zJlIvVZneqjrExOcBy8p/bFK5IIppd/vQ5nYXvdIpB6S9mwPe3UPAqimlyG+K4tjhpm9CZbw6zG8vlTOy1ZiUo7d6wtyiK0V/fCPkoV2bhDE13hOhfkbdYD04jsTHifhqklPko1uh5V7GzzT6MzAMW3Hv0TsL4UCZpNcZ89ZGJhY9xZjzgP/SiwE7UTuNvZSo6OwWpsP7dNk9+tRIuupHu+4uVVzxQ3ERMBixzsks8mFlQE="
  on:
    tags: true
  skip_cleanup: true
